#:schema node_modules/wrangler/config-schema.json
name = "backend"
main = "src/index.ts"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
exclude = ["seed"]

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "toxicity"

[ai]
binding = "AI"