#:schema node_modules/wrangler/config-schema.json
name = "toxicity-api"
main = "src/index.ts"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[[vectorize]]
binding = "VECTORIZE"
index_name = "toxicity-api"

[ai]
binding = "AI"